### ISSUE TITLE
Custom HMMs

### ISSUE THREAD

**Issue by cem204** [ncbi/ITSx#1]
Is it possible to input my own HMMs? I'd like to detect ITS sequences utilizing some dinoflagellate (symbiodiniceae) HMMs I've generated, but it seems that ITSx will only allow me to align to the default profiles- even when I specify a separate directory that only contains my own HMMs. Any suggestions? Thanks!

**Comment by stairsb** [comment]
I also am having this issue

**Comment by tgs** [comment]
Hello,
This GitHub repository just holds NCBI's wrapper around ITSx - the actual authors and maintainers of ITSx do not monitor this repository. You should look at the ITSx home page at https://microbiology.se/software/itsx/ - you'll find the author's e-mail there.

(This repository exists because we needed to modify the ITSx script, and the license requires us to publish those changes.)

Hope this helps and good luck!
