### ISSUE TITLE
Unexpectedly long run times

### ISSUE THREAD

**Issue by Lamm-a** [ncbi/ITSx#2]
I am running ITSx on some symbiotic fungi of between 40 to 60mb using 32gb RAM 2 cores yet run time is exceeding 2 hours.

Is this expected?

**version**

`1.1.3`

**Input**

`perl /home/projects/ku_00014/people/robmur/programmes/ITSx_1.1.3/ITSx -i $input -o $outdir`

**Output**

```
ITSx -- Identifies ITS sequences and extracts the ITS region
by Johan Bengtsson-Palme et al., University of Gothenburg
Version: 1.1.3
-----------------------------------------------------------------
Mon Mar  1 15:56:56 2021 : Preparing HMM database (should be quick)...
Mon Mar  1 15:56:56 2021 : Checking and handling input sequence data (should not take long)...
Mon Mar  1 15:56:58 2021 : Comparing sequences to HMM database (round 1 of 3)...
```

**Comment by tgs** [comment]
Hello, thanks for getting in touch!
This GitHub repository is not monitored by the author of ITSx - you should look at the ITSx home page at https://microbiology.se/software/itsx/ .  You'll find both a link to a parallel implementation that might help, and the e-mail address of the ITSx author.

(This repository exists because we needed to modify the ITSx script, and the license requires us to publish those changes.)

Hope this helps and good luck!
