### ISSUE TITLE
over comparison pipeline limit

### ISSUE THREAD

**Issue by Niohuruzh** [ncbi/ITSx#3]
Hi ITSx team
I want ues `ITSx` software to detect the ITS sequence while the `blastn` software can't detect any ITS sequence from a fasta file about 17M which downloaded from NCBI. However, when I use `ITSx` with command: `ITSx -i 99_473.fna -o 99_473`
There is an error:
```
ITSx -- Identifies ITS sequences and extracts the ITS region
by Johan Bengtsson-Palme et al., University of Gothenburg
Version: 1.1.3
-----------------------------------------------------------------
Thu Jan 27 08:34:47 2022 : Preparing HMM database (should be quick)...
Thu Jan 27 08:34:47 2022 : Checking and handling input sequence data (should not take long)...
Thu Jan 27 08:34:58 2022 : Comparing sequences to HMM database (round 1 of 1)...
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
ERROR! HMMER search terminated unexpectedly.
```
There is anyway to expand the length to detect? 
Looking for your reply
Best regards

**Comment by kellystyles** [comment]
I had large chromosome-sized scaffolds from a long-read assembly and got around this error by using the `--nhmmer T` parameter. This uses nhmmer, a program similar to hmmsearch that is optimized for long sequences. 
Hope this helps!

**Comment by tgs** [comment]
Hello,
This GitHub repository just holds NCBI's wrapper around ITSx - the actual authors and maintainers of ITSx do not monitor this repository.  You should look at the ITSx home page at https://microbiology.se/software/itsx/ - you'll find the author's e-mail there.

@kellystyles thank you for helping out :)


(This repository exists because we needed to modify the ITSx script, and the license requires us to publish those changes.)

Hope this helps and good luck!
